#!/bin/bash

CONFIG="$HOME/Dotfiles/scripts/wofimenu/config.ini"
STYLE="$HOME/Dotfiles/scripts/wofimenu/style.css"
COLORS="$HOME/Dotfiles/scripts/wofimenu/colors"

if [[ ! $(pidof wofi) ]]; then
	wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
	pkill wofi
fi
